- name: "Configurando dns..."
  copy:
    src: resolv.conf-client
    dest: /etc/resolv.conf
    owner: root
    group: root
    mode: '0644'

- name: Actualizar paquetes
  become: true
  apt: update_cache=yes upgrade=yes

#- name: Install ssh key
#  authorized_key: user=usuario
#                  key="{{lookup('file', '/home/retr0/.ssh/id_rsa.pub')}}"
